/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MastodonStatus {
        "instance": string;
        "statusId": string;
    }
}
declare global {
    interface HTMLMastodonStatusElement extends Components.MastodonStatus, HTMLStencilElement {
    }
    var HTMLMastodonStatusElement: {
        prototype: HTMLMastodonStatusElement;
        new (): HTMLMastodonStatusElement;
    };
    interface HTMLElementTagNameMap {
        "mastodon-status": HTMLMastodonStatusElement;
    }
}
declare namespace LocalJSX {
    interface MastodonStatus {
        "instance": string;
        "statusId": string;
    }
    interface IntrinsicElements {
        "mastodon-status": MastodonStatus;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mastodon-status": LocalJSX.MastodonStatus & JSXBase.HTMLAttributes<HTMLMastodonStatusElement>;
        }
    }
}
